# Site settings
title: Ruby Not Rails
email: britney@britneywright.com
description: "First comes language, then comes framework. Ruby development interviews and inspiration."
baseurl: "/ruby-not-rails" # the subpath of your site, e.g. /blog/
url: "http://rubynotrails.com" # the base hostname & protocol for your site
twitter_username: britneywright
paginate: 2

# Build settings
markdown: kramdown
